server:
  port: 8086
  host: localhost
spring:
  application:
    name: eureka-client
eureka:
  instance:
    hostname: eureka-client
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${server.host}:8083/eureka/,http://${server.host}:8084/eureka/,http://${server.host}:8085/eureka/
    registry-fetch-interval-seconds: 30
    eureka-service-url-poll-interval-seconds: 10
ribbon:
  MaxAutoRetriesNextServer: -1
feign:
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true # You may consider enabling the request or response GZIP compression for your Feign requests. You can do this by enabling one of the properties:
    response:
      enabled: true
